services:
  server:
    container_name: "password_store_server"
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      # - COOKIE_NAME=${}
      # - COOKIE_EXPIRY_DURATION=${}
      # - COOKIE_RANDOM_STRING_LENGTH=${}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  redis:
    container_name: "password_store_redis"
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  db:
    container_name: "password_store_db"
    image: postgres:14
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1s
      timeout: 5s
      retries: 10